### ISSUE TITLE
Maxical details on demand issues

### ISSUE THREAD

**Issue by Gerg** [courseshark/courseshark#112]
Times are wrong and location is not in the DoD.
![Screen Shot 2013-01-08 at 4 10 58 PM](https://f.cloud.github.com/assets/875892/51634/f0b12fa0-59d7-11e2-919a-ca5a98608da7.png)

**Comment by Gerg** [comment]
Also (maybe in another issue), we should probably make the dod logic a bit smarter about whether it displays above or below the class based on calendar position.

**Comment by jrundquist** [comment]
![Screen Shot 2013-01-10 at 10 31 57 PM](https://f.cloud.github.com/assets/1072063/59107/72c4b656-5b9f-11e2-8208-1a39fa3c223a.png)
Loss of leading 0 in minutes if <10

**Comment by jrundquist** [comment]
Seat numbers all 0

![Screen Shot 2013-01-10 at 10 41 46 PM](https://f.cloud.github.com/assets/1072063/59128/dbf16772-5ba0-11e2-86bd-003fe9eaac17.png)

Ensure the view updates when the section updates.
