### ISSUE TITLE
Facebook/Twitter login failing

### ISSUE THREAD

**Issue by jrundquist** [courseshark/courseshark#30]
The everyauth module fails out when logging in with Facebook or Twitter. Google seems unaffected.

**Comment by jrundquist** [comment]
Seems Twitter ( and presumably Facebook as well ) updated their API urls, and the Everyauth code cannot handle the new error message styles posted back by the services. 

Updating the Everyauth module to v0.3.1 seems to have fixed the issue. 

With the update we had to update some code to meet the new Everyauth paradigms.

**Comment by jrundquist** [comment]
Fixed and launched.

**Comment by jrundquist** [comment]
Facebook and Google returning failures based on redirect-url? 

FB:
{"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100}}

**Comment by jrundquist** [comment]
Fixed by the Ghost in the Machine ( which we should name )

**Comment by amarchenkova** [comment]
Facebook still failing, same error

**Comment by jrundquist** [comment]
Alright I'll check it out again when I get back from breakfast (WestEgg ftw)

Sent from my iPhone

On Oct 20, 2012, at 11:24 AM, amarchenkova notifications@github.com wrote:

Facebook still failing, same error

—
Reply to this email directly or view it on
GitHubhttps://github.com/courseshark/courseshark/issues/30#issuecomment-9632330.

**Comment by jrundquist** [comment]
Set loadbalancer to sticky sessions. Error seems to have gone.
