### ISSUE TITLE
Phys 2211 & 2212 not showing up

### ISSUE THREAD

**Issue by amarchenkova** [courseshark/courseshark#32]
no classes showing up. Could be because of lab sections?

**Comment by jrundquist** [comment]
Fixed, they show up but labs are not grouping and are missing timeslots.

**Comment by jrundquist** [comment]
Fixed, they show up but labs are not grouping and are missing timeslots.

On Thu, Oct 18, 2012 at 2:12 PM, amarchenkova notifications@github.comwrote:

> no classes showing up. Could be because of lab sections?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/courseshark/courseshark/issues/32.

## 

James Rundquist
