### ISSUE TITLE
Details on Demand for MaxiCal 

### ISSUE THREAD

**Issue by jrundquist** [courseshark/courseshark#90]
slide-container overlays atop maxical stopping details on demand.

**Comment by Gerg** [comment]
This same issue also breaks scrolling on the Maxical.  The slide panel eats all the scrolling for the Maxical, so if you resize your window to be too short, you cannot scroll to see all your classes.

**Comment by jrundquist** [comment]
Pull #91 fixed it for the larger size, but the new changes introduced a problem when the site responsives itself into smaller size. Should be fixed with media-queries.

**Comment by jrundquist** [comment]
Pull request #95 addresses this issue.
